# Generated by Django 2.1.2 on 2018-10-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condiciones',
            name='Plazo',
        ),
        migrations.AddField(
            model_name='condiciones',
            name='PlazoMeses',
            field=models.CharField(choices=[('6', '6 Meses'), ('12', '12 Meses'), ('18', '18 Meses'), ('24', '24 Meses')], default='6', max_length=2),
        ),
    ]
