# Generated by Django 2.1.2 on 2018-10-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_auto_20181009_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condiciones',
            old_name='InteresAnual',
            new_name='Intanual',
        ),
        migrations.RenameField(
            model_name='plazos',
            old_name='cantidad',
            new_name='ncuotas',
        ),
    ]
