# Generated by Django 2.1.2 on 2018-10-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0005_auto_20181009_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreciosIni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onixsat1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('btcusd1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('btcves1', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
