# Generated by Django 2.1.2 on 2018-10-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0006_preciosini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciosini',
            name='btcusd1',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='preciosini',
            name='btcves1',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='preciosini',
            name='onixsat1',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
