# Generated by Django 2.1.2 on 2018-10-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0007_auto_20181009_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreciosIni',
            new_name='PreciosIniciales',
        ),
    ]
