# Generated by Django 2.1.2 on 2018-10-19 21:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0008_auto_20181009_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_us', models.DateTimeField(default=django.utils.timezone.now)),
                ('Interes_us', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ME_ONIX_us', models.DecimalField(decimal_places=8, max_digits=15)),
                ('Transferido_VES_us', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MP_ONX_us', models.DecimalField(decimal_places=8, max_digits=15)),
                ('Garantia_us', models.DecimalField(decimal_places=8, max_digits=15)),
                ('Pena_Mora_us', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Cuotas_Impago_us', models.IntegerField()),
                ('Usuario_us', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculadora.Usuario')),
            ],
        ),
    ]
