# Generated by Django 2.1.2 on 2018-10-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0010_auto_20181019_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo_us',
            name='User',
        ),
        migrations.DeleteModel(
            name='Prestamo_us',
        ),
    ]
