# Generated by Django 2.1.2 on 2018-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0011_auto_20181019_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=35, max_length=8),
            preserve_default=False,
        ),
    ]
