# Generated by Django 2.1.2 on 2018-10-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0012_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
