# Generated by Django 2.1.2 on 2018-10-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculadora', '0014_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='FechaPrestamo',
            new_name='Fecha_Prestamo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='PlazoMeses',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='monto',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Plazo',
            field=models.TextField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Usuario',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
