# Generated by Django 2.1.2 on 2018-10-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0015_auto_20181022_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='Plazo',
        ),
    ]
