# Generated by Django 2.1.2 on 2018-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0016_remove_prestamo_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='monto',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_Prestamo',
            field=models.DateField(),
        ),
    ]
