# Generated by Django 2.1.2 on 2018-10-23 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0018_remove_prestamo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_Prestamo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
