# Generated by Django 2.1.2 on 2018-10-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0021_auto_20181023_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='monto',
            new_name='monto_ONX_Prestamo',
        ),
        migrations.AlterField(
            model_name='preciosiniciales',
            name='btcusd1',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='preciosiniciales',
            name='onixsat1',
            field=models.DecimalField(decimal_places=8, max_digits=17),
        ),
    ]
