# Generated by Django 2.1.2 on 2018-10-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0023_auto_20181023_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='Plazo_Cuotas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
