# Generated by Django 2.1.2 on 2018-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0024_prestamo_plazo_cuotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Cuotas_Garantia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
