# Generated by Django 2.1.2 on 2018-10-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0025_auto_20181023_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='Cuota_Capital',
            new_name='Capital_Mensual',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Cuota_Mensual',
            new_name='Cuota_ONX',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Plazo_Cuotas',
            new_name='Cuotas_Mensuales',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Garantia',
            new_name='Garantia_ONX',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Cuotas_Garantia',
            new_name='Impagos_Posibles',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Couota_Interes',
            new_name='Interes_Mensual',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Monto',
            new_name='Monto_ONX',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Penalidad',
            new_name='Penalidad_Mora',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Transferido',
            new_name='Transferido_BsS',
        ),
    ]
