# Generated by Django 2.1.2 on 2018-10-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0026_auto_20181023_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciosiniciales',
            name='btcusd1',
        ),
    ]
